const questions = [
  {
    id: 1,
    q: "Which sentence is a <em class='bold'>command</em>?",
    choices: [
      "The relay race will be next.",
      "I hope I don't drop the baton.",
      "Run as fast as you can",
      "I know you can win this race",
    ],
    answer: 2,
    questionRef: "2023-paper1-q1",
  },
  {
    id: 2,
    q: "Is this sentence an <em class='bold'>exclamation</em> or a <em class='bold'>question</em>?",
    q2: "'How disappointing it was that it rained on sports day'",
    choices: ["Exclamation", "Question"],
    answer: 0,
    questionRef: "2023-paper1-q2a",
  },

  {
    id: 3,
    q: "Is this sentence an exclamation or a question?",
    q2: "'How many times have you been to the swimming pool this week'",
    choices: ["Exclamation", "Question"],
    answer: 1,
    questionRef: "2023-paper1-q2b",
  },

  {
    id: 4,
    q: "Is this sentence an exclamation or a question?", 
    q2: "'How will you spend your summer holidays'",
    choices: ["Exclamation", "Question"],
    answer: 1,
    questionRef: "2023-paper1-q2c",
  },

  {
    id: 5,
    q: "Is this sentence an exclamation or a question?",
    q2: "'How kind you are to give me this present'",
    choices: ["Exclamation", "Question"],
    answer: 0,
    questionRef: "2023-paper1-q2d",
  },

  {
    id: 6,
    q: "Which sentence is written in <em class='bold'>Standard English</em>?",
    choices: [
      "The autumn leaves was crunching beneath our feet as we walked along.",
      "The autumn leaves were crunching beneath our feet as we walked along.",
    ],
    answer: 1,
    questionRef: "2023-paper1-q5a",
  },

  {
    id: 7,
    q: "Which sentence is written in <em class='bold'>Standard English</em>?",
    choices: [
      "We done a great job in picking the juiciest fruit for our pie.",
      "We did a great job in picking the juiciest fruit for our pie.",
    ],
    answer: 1,
    questionRef: "2023-paper1-q5b",
  },

  {
    id: 8,
    q: "Which sentence is written in <em class='bold'>Standard English</em>?",
    choices: [
      "My brother didn't do anything to help us.",
      "My brother didn't do nothing to help us.",
    ],
    answer: 0,
    questionRef: "2023-paper1-q5b",
  },
  {
    id: 9,
    q: "Which pair of words are <em class='bold'>antonyms</em>?",
    choices: [
      "marine submarine",
      "unicycle bicycle",
      "proper improper",
      "act interact",
    ],
    answer: 2,
    questionRef: "2023-paper1-q6",
  },
  {
    id: 11,
    q: "Which sentence is the most <em class='bold'>formal</em>?",
    choices: [
      "We can't keep your things here, as there's no room.",
      "It is essential that you take all your belongings with you.",
      "Please pack up all your stuff before you leave.",
      "It's time to get all your bits and pieces together.",
    ],
    answer: 1,
    questionRef: "2023-paper1-q9",
  },
  {
    id: 12,
    q: "Which sentence is punctuated correctly?",
    choices: [
      "Charlie's party, which was at the ice rink was really enjoyable.",
      "Charlie's party which was at the ice rink, was really enjoyable.",
      "Charlie's party, which was at the ice rink, was really enjoyable.",
      "Charlie's party which, was at the ice rink, was really enjoyable.",
    ],
    answer: 2,
    questionRef: "2023-paper1-q11",
  },
  {
    id: 13,
    q: "In which sentence is <em class='underline'>plant</em> a <em class='bold'>verb</em>?",
    choices: [
      "The recycling <em class='underline'>plant</em> was closed for the weekend.",
      "The children <em class='underline'>plant</em> beans in the school garden.",
      "I remember to water my <em class='underline'>plant</em> every day.",
      "The roses were growing in a <em class='underline'>plant</em> pot.",
    ],
    answer: 1,
    questionRef: "2023-paper1-q12",
  },
  {
    id: 14,
    q: "Which sentence is the most <em class='bold'>formal</em>?",
    choices: [
      "I asked him to phone me when he got here.",
      "I told him to call me as soon as he turned up.",
      "I got him to ring me when he came in.",
      "I requested that he telephone me on arrival.",
    ],
    answer: 3,
    questionRef: "2023-paper1-q14",
  },
  {
    id: 15,
    q: "Is the apostrophe in this sentence used for a <em class='bold'>contracted form</em> or <em class='bold'>possession</em>?", 
    q2: "'Let's hope it warms up soon.'",
    choices: ["Contracted form", "Possession"],
    answer: 0,
    questionRef: "2023-paper1-q17a",
  },
  {
    id: 16,
    q: "Is the apostrophe in this sentence used for a <em class='bold'>contracted form</em> or <em class='bold'>possession</em>?",
    q2: "'The teachers' coats were hanging in the staffroom.'",
    choices: ["Contracted form", "Possession"],
    answer: 1,
    questionRef: "2023-paper1-q17b",
  },
  {
    id: 17,
    q: "Is the apostrophe in this sentence used for a <em class='bold'>contracted form</em> or <em class='bold'>possession</em>?",
    q2: "'The children wear their scarves when it's cold.'",
    choices: ["Contracted form", "Possession"],
    answer: 0,
    questionRef: "2023-paper1-q17c",
  },
  {
    id: 18,
    q: "Which option completes the sentence using the <em class='bold'>present progressive</em>?", 
    q2:"'I _________ the photos to the school website.'",
    choices: ["upload", "will upload", "have uploaded", "am uploading"],
    answer: 3,
    questionRef: "2023-paper1-q18",
  },
  {
    id: 19,
    q: "Which sentence uses <em class='bold'>tense</em> correctly?",
    choices: [
      "She is getting the ball and then she scored the winning goal.",
      "My friends thought the film was good, but I don't like thrillers.",
      "When the clock strikes midnight, everyone was in bed.",
      "Tonight he is playing rounders and she joined in.",
    ],
    answer: 1,
    questionRef: "2023-paper1-q19",
  },
  {
    id: 20,
    q: "Which sentence is punctuated correctly?",
    choices: [
      "Erin wanted the most up-to date computer that was available.",
      "Erin wanted the most-up-to-date computer that was available.",
      "Erin wanted the most up-to-date-computer that was available.",
      "Erin wanted the most up-to-date computer that was available.",
    ],
    answer: 3,
    questionRef: "2023-paper1-q28",
  },
  {
    id: 21,
    q: "What are the underlined words in the sentence below?", 
    q2: "<em class='underline'>The girl with curly red hair</em> is in my class.",
    choices: [
      "a relative clause",
      "a subordinate clause",
      "a main clause",
      "a noun phrase",
    ],
    answer: 3,
    questionRef: "2023-paper1-q33",
  },
  {
    id: 22,
    q: "Which sentence uses a <em class='bold'>semi-colon</em> correctly?",
    choices: [
      "In the bag we found; five carrots, two cabbages and a large onion.",
      "The book began with a boy called Tim; climbing a steep hill.",
      "Jessie went to look for her brother; Bill.",
      "The wind was howling; the rain was drumming on the roof.",
    ],
    answer: 3,
    questionRef: "2023-paper1-q38",
  },
  {
    id: 23,
    q: "Is <em class='underline'>once</em> an <em class='bold'>adverb</em> or a <em class='bold'>conjunction</em> in the sentence below?", 
    q2: "'I've only been to France <em class='underline'>once</em> with my family.'",
    choices: ["adverb", "conjunction"],
    answer: 0,
    questionRef: "2023-paper1-q50a",
  },
  {
    id: 24,
    q: "Is <em class='underline'>once</em> an <em class='bold'>adverb</em> or a <em class='bold'>conjunction</em> in the sentence below?",  
    q2: "'<em class='underline'>Once</em> I arrived in Paris, I tried to speak French.'",
    choices: ["adverb", "conjunction"],
    answer: 1,
    questionRef: "2023-paper1-q50b",
  },
  {
    id: 25,
    q: "Is <em class='underline'>once</em> an <em class='bold'>adverb</em> or a <em class='bold'>conjunction</em> in the sentence below?", 
    q2: "'My accent really improved <em class='underline'>once</em> we had been there a few days.'",
    choices: ["adverb", "conjunction"],
    answer: 1,
    questionRef: "2023-paper1-q50c",
  },
  {
    id: 26,
    q: "Which sentence must end with a <em class='bold'>question mark</em>? Select one.",
    choices: [
      "Shall we go round the fitness trail in the park",
      "We could go tomorrow if you like",
      "What I really like is the rope bridge",
      "Let me know what you would like to do",
    ],
    answer: 0,
    questionRef: "2022-paper1-q4",
  },
  {
    id: 27,
    q: "Which sentence is punctuated correctly? Select one.",
    choices: [
      "Nevertheless we, are going on Saturday.",
      "Finally, I think I understand what you mean.",
      "Considering, all his efforts the result was disappointing.",
      "At the last, count there were twenty people coming.",
    ],
    answer: 1,
    questionRef: "2022-paper1-q5",
  },
  {
    id: 28,
    q: "Which sentence uses <em class='bold'>commas</em> correctly?",
    choices: [
      "The band will perform at concerts in Belfast, Manchester, Birmingham, Nottingham and, Sheffield.",
      "The children could choose to play netball, cricket, hockey or tennis.",
      "Owls badgers, hedgehogs and bats are all nocturnal animals.",
      "Painting, drawing, sculpture and print-making, were all options on the art day.",
    ],
    answer: 1,
    questionRef: "2022-paper1-q6",
  },
  {
    id: 29,
    q: "Which sentence is punctuated correctly? Select one",
    choices: [
      "Add one ounce (around one) tablespoon of yeast to your bread mix.",
      "Add one ounce around one tablespoon of yeast (to your bread mix).",
      "Add one ounce (around one tablespoon) of yeast to your bread mix.",
      "Add one ounce around (one tablespoon) of yeast to your bread mix.",
    ],
    answer: 2,
    questionRef: "2022-paper1-q7",
  },
  {
    id: 30,
    q: "Which sentence expresses the greatest certainty? Select one.",
    choices: [
      "It may rain later in the week.",
      "The train might arrive late again today.",
      "I will walk through the park to get to school.",
      "It should be sunny and warm tomorrow.",
    ],
    answer: 2,
    questionRef: "2022-paper1-q8",
  },
  {
    id: 31,
    q: "What does the word <em class='underline'>them</em> refer to in the sentence below?", 
    q2: "Although deserts are very dry, a rich variety of plants and animals can survive in <em class='underline'>them</em>.",
    choices: ["deserts", "variety", "plants", "animals"],
    answer: 0,
    questionRef: "2022-paper1-q10",
  },
  {
    id: 32,
    q: "What is the <em class='bold'>word class</em> of the underlined words?",
    q2: "I have two brothers. Brian is <em class='underline'>older</em> and Stanley is <em class='underline'>younger</em> than me.",
    choices: ["adjective", "noun", "adverb", "verb"],
    answer: 0,
    questionRef: "2022-paper1-q15",
  },
  {
    id: 33,
    q: "Which sentence is the most formal? Select one.",
    choices: [
      "Getting enough sleep is important, isn't it?",
      "Let's set off early for school tomorrow.",
      "Do you fancy coming with us to the park?",
      "It is essential that we remember our water bottles.",
    ],
    answer: 3,
    questionRef: "2022-paper1-q17",
  },
  {
    id: 34,
    q: "Which option is punctuated correctly? Select one.",
    choices: ["He is famous for his innovative music: a mix of recorded noises, traditional instruments and songs.", "He is famous for his innovative music. a mix of recorded noises, traditional instruments and songs.", "He is famous for his innovative music; a mix of recorded noises, traditional instruments, and songs.", "He is famous for his innovative music, (a mix of recorded noises, traditional instruments and songs)."],
    answer: 0,
    questionRef: "2022-paper1-q23",
  },
  {
    id: 35,
    q: "What are the <em class='bold'>word classes</em> of the underlined words?", 
    q2: "The <em class='underline'>erosive</em> force of the sea <em class='underline'>erodes</em> the coastline.",
    choices: ["noun adjective", "adjective verb", "noun verb", "adjective adverb"],
    answer: 1,
    questionRef: "2022-paper1-q26",
  },
  {
    id: 36,
    q: "What is the sentence below?", 
    q2: "'Safiya asked the teacher which page we had to read.'",
    choices: ["a question", "a command", "a statement", "an exclamation"],
    answer: 2,
    questionRef: "2022-paper1-q28",
  },
  {
    id: 37,
    q: "How does the use of the <em class='underline'>passive</em> in the second sentence affect the way the information is presented?",
    q2: "1. Max dropped the red bucket.",
    q3: "2. The red bucket was dropped.",
    choices: ["It does not say who dropped the bucket.", "It shows that the action happened in the past.", "It shows that it was an accident.", "It does not say why the bucket was dropped."],
    answer: 0,
    questionRef: "2022-paper1-q29",
  },
  {
    id: 38,
    q: "Which option makes the sentence start with an <em class='bold'>adverbial</em>?", 
    q2: "_________ we lined up for the class photo.",
    choices: ["It was noisy and crowded, but", "The photographer arrived while", "With big smiles on our faces,", "The whole class were ready so"],
    answer: 2,
    questionRef: "2022-paper1-q36",
  },
  {
    id: 39,
    q: "Is the following sentence written in <em class='bold'>Standard</em> or <em class='bold'>non-Standard</em> English?", 
    q2: "'I were going to keep the picture to show you.'",
    choices: ["standard", "non-standard"],
    answer: 1,
    questionRef: "2022-paper1-q42a",
  },
  {
    id: 40,
    q: "Is the following sentence written in <em class='bold'>Standard</em> or <em class='bold'>non-Standard</em> English?",
    q2: "'We was helping to design the new school building'",
    choices: ["standard", "non-standard"],
    answer: 1,
    questionRef: "2022-paper1-q42a",
  },
  {
    id: 41,
    q: "Is the following sentence written in <em class='bold'>Standard</em> or <em class='bold'>non-Standard</em> English?", 
    q2: "'He doesn't know nothing about football'",
    choices: ["standard", "non-standard"],
    answer: 1,
    questionRef: "2022-paper1-q42a",
  },
  { 
    id: 42,
    q: "Is the following sentence written in <em class='bold'>Standard</em> or <em class='bold'>non-Standard</em> English?", 
    q2: "'I have done all the washing-up.'",
    choices: ["standard", "non-standard"],
    answer: 0,
    questionRef: "2022-paper1-q42a",
  },
  {
    id: 43,
    q: "What is the grammatical term for the underlined words in the sentence below?", 
    q2: "<em class='underline'>The majestic lioness under the shady tree</em> watched her cubs play.",
    choices: ["a fronted adverbial",
    "a subordinate clause",
    "a main clause",
    "a noun phrase"],
    answer: 3,
    questionRef: "2022-paper1-q44",
  },
  {
    id: 44,
    q: "Below is a sentence containing an <em class='bold'>apostrophe</em> followed by a statement about the sentence. Choose whether the statement is <em class='bold'>true</em> or <em class='bold'>false</em>.", 
    q2: "'Gina put out the cats' food.'",
  q3: " There is more than one cat.",
    choices: ["true", "false"],
    answer: 0,
    questionRef: "2022-paper1-q45a",
  },
  {
    id: 45,
    q: "Below is a sentence containing an <em class='bold'>apostrophe</em> followed by a statement about the sentence. Choose whether the statement is <em class='bold'>true</em> or <em class='bold'>false</em>.", 
    q2: "'The girl's party is this afternoon.'",
  q3: "There is more than one girl.",
    choices: ["true", "false"],
    answer: 1,
    questionRef: "2022-paper1-q45b",
  },
  {
    id: 46,
    q: "Below is a sentence containing an <em class='bold'>apostrophe</em> followed by a statement about the sentence. Choose whether the statement is <em class='bold'>true</em> or <em class='bold'>false</em>.",
    q2: "'The trees' leaves were green.'",
  q3: "There is only one tree.",
    choices: ["true", "false"],
    answer: 1,
    questionRef: "2022-paper1-q45c",
  },
  {
    id: 47,
    q: "Below is a sentence containing an <em class='bold'>apostrophe</em> followed by a statement about the sentence. Choose whether the statement is <em class='bold'>true</em> or <em class='bold'>false</em>.",
    q2: "'The boys' lunch was delicious.'",
      q3: "There is only one boy.",
    choices: ["true", "false"],
    answer: 1,
    questionRef: "2022-paper1-q45d",
  },
  {
    id: 48,
    q: "What is the grammatical term for the underlined words in the sentence below?",
    q2: "'Nathan <em class='underline'>had hoped</em> for a part in the school play.'",
    choices: ["Simple past", "Past progressive", "Past perfect"],
    answer: 2,
    questionRef: "2022-paper1-q49a",
  },
  {
    id: 49,
    q: "What is the grammatical term for the underlined words in the sentence below?", 
    q2: "The children <em class='underline'>were rehearsing</em> their lines.",
    choices: ["Simple past", "Past progressive", "Past perfect"],
    answer: 1,
    questionRef: "2022-paper1-q49b",
  },
  {
    id: 50,
    q: "What is the grammatical term for the underlined words in the sentence below?", 
    q2: "Lots of parents <em class='underline'>came</em> to watch.",
    choices: ["Simple past", "Past progressive", "Past perfect"],
    answer: 0,
    questionRef: "2022-paper1-q49c",
  },
  {
    id: 51,
    q: "Select the sentence that must end with a question mark.",
    choices: ["The teacher asked them what they were doing", "I wonder what time the next train arrives", "Did she play tennis on your team last year", "He asked if he could use my pen"],
    answer: 2,
    questionRef: "2019-paper1-q1",
  },
  {
    id: 52,
    q: "Is the following sentence a <em class='bold'>question</em> or a <em class='bold'>command</em>?",
    q2: "'Do your stretches before you exercise'",
    choices: ["Question", "Command"],
    answer: 1,
    questionRef: "2019-paper1-q3a",
  }, {
    id: 53,
    q: "Is the following sentence a <em class='bold'>question</em> or a <em class='bold'>command</em>?",
    q2: "'Do you prefer tennis or cricket'",
    choices: ["Question", "Command"],    
    answer: 0,
    questionRef: "2019-paper1-q3b",
  },  {
    id: 54,
    q: "Is the following sentence a <em class='bold'>question</em> or a <em class='bold'>command</em>?",
    q2: "'Do the boys always go running in the morning'",
    choices: ["Question", "Command"],
    answer: 0,
    questionRef: "2019-paper1-q3c",
  },  {
    id: 55,
    q: "Is the following sentence a <em class='bold'>question</em> or a <em class='bold'>command</em>?",
    q2: "'Do take some water with you to football practice'",
    choices: ["Question", "Command"],
    answer: 1,
    questionRef: "2019-paper1-q3d",
  },  
  {
    id: 56,
    q: "Which sentence must <em class='bold'>not</em> end with an <em class='bold'>exclamation mark</em>?",
    choices: ["What a dreadful day I had", "What is the temperature now", "The wind is very strong today", "You really must wear a coat"],
    answer: 1,
    questionRef: "2019-paper1-q6",
  },
   {
    id: 57,
    q: "In which sentence is <em class='underline'>lock</em> a <em class='bold'>verb</em>?",
    choices: ["Aisha closed the box and fastened the <em class='underline'>lock</em>.", "Make sure you <em class='underline'>lock</em> the gate before you leave", "I think I need to buy a new bike <em class='underline'>lock</em>.", "The <em class='underline'>lock</em> can only be opened with this special key."],
    answer: 1,
    questionRef: "2019-paper1-q9",
  },  {
    id: 58,
    q: "What does the <em class='bold'>prefix</em> <em class='underline'>multi-</em> mean in the words multicultural, multipurpose and multicoloured?",
    choices: ["some", "few", "all", "many"],
    answer: 3,
    questionRef: "2019-paper1-q12",
  },  {
    id: 59,
    q: "Which sentence is punctuated correctly?",
    choices: ["I will be running - a half marathon 13 miles next week!", "I will be - running a half marathon - 13 miles next week!", "I will be running a half marathon 13 - miles - next week!", "I will be running a half marathon - 13 miles - next week!"],
    answer: 3,
    questionRef: "2019-paper1-q13",
  },  {
    id: 60,
    q: "Which word is an <em class='bold'>antonym</em> of <em class='underline'>difficult</em>?",
    q2: "The problem was <em class='underline'>difficult</em> to solve.",
    choices: ["hard", "easy", "impossible", "challenging"],
    answer: 1,
    questionRef: "2019-paper1-q15",
  },  {
    id: 61,
    q: "Which sentence is the most <em class='bold'>formal</em>?",
    choices: ["The way they played was terrible, wasn't it?", "I wish they'd put a little more effort in today!", "If only they'd tried a bit harder, they would've won.", "The team were defeated due to mistakes that they made."],
    answer: 3,
    questionRef: "2019-paper1-q15",
  },  
  {
    id: 62,
    q: "What <em class='bold'>word class</em> is <em class='underline'>him</em> in the sentence below?",
    q2: "Josef's friends rushed to meet <em class='underline'>him</em>, desperate to see if he had won.",
    choices: ["a preposition", "an adjective", "a pronoun", "a noun"],
    answer: 2,
    questionRef: "2019-paper1-q17",
  },  {
    id: 63,
    q: "What is the <em class='bold'>word class</em> of the underlined word?",
    q2: "Our school is bigger than <em class='underline'>theirs</em>.",
    choices: ["a co-ordinating conjunction", "a subordinating conjunction", "a possessive pronoun", "a relative pronoun"],
    answer: 2,
    questionRef: "2019-paper1-q21",
  },  {
    id: 64,
    q: "Which sentence uses <em class='bold'>tense</em> correctly?",
    choices: ["We sat and ate our lunch once we had found a sunny picnic spot.", "Once we find a sunny picnic spot, we sat and ate our lunch.", "Once we had found a sunny picnic spot, we sit and eat our lunch.", "We sat and eat our lunch once we had found a sunny picnic spot."],
    answer: 0,
    questionRef: "2019-paper1-q24",
  },  {
    id: 65,
    q: "Which sentence is closest in meaning to the one below?",
    q2: "My dad has had this bike for two years.",
    choices: ["My dad no longer has this bike.", "My dad is having this bike for his birthday.", "My dad has this bike now.", "My dad will have a bike in two years' time."],
        answer: 2,
    explanation: "My dad has had this bike for two years and he still has it",
    questionRef: "2019-paper1-q29",
  },  {
    id: 66,
    q: "Which sentence is punctuated correctly?",
    choices: ["Our parents always say “work hard and do your best.” ", "Our parents always say, “work hard and do your best.” ", "Our parents always say, “Work hard and do your best.” ", "Our parents always say “Work hard and do your best.” "],
    answer: 2,
    explanation: "Introduce quotes with a comma and start them with a capital letter",
    questionRef: "2019-paper1-q31",
  }, {
    id: 67,
    q: "Which underlined word is an <em class='bold'>adverb</em>?",
    choices: ["The spring garden looks <em class='underline'>lovely</em>.", "My little sister has a <em class='underline'>wobbly</em> tooth.", "The clothes are folded <em class='underline'>neatly</em>.", "Her brown hair is long and <em class='underline'>curly</em>."],
    answer: 2,
    questionRef: "2019-paper1-q32",
  },  {
    id: 68,
    q: "Which sentence uses the <em class='bold'>passive<em class='bold'>?",
    choices: ["The school proposed building a new playground.", "The issue was discussed at a council meeting.", "The council voted in favour of the proposal.", "They started building the new playground last week."],
    answer: 1,
    questionRef: "2019-paper1-q42",
  },  
  {
    id: 69,
    q: "Select one option to show whether the underlined word is a <em class='bold'>verb</em>, a <em class='bold'>noun</em> or an <em class='bold'>adjective</em>.",
    q2: "There are many <em class='underline'>magnetic</em> materials",
    choices: ["Verb", "Noun", "Adjective"],
    answer: 2,
    questionRef: "2023-paper1-q22a",
  },  {
    id: 70,
    q: "Select one option to show whether the underlined word is a <em class='bold'>verb</em>, a <em class='bold'>noun</em> or an <em class='bold'>adjective</em>.",
    q2: "<em class='underline'>Magnets</em> attract some metals",
    choices: ["Verb", "Noun", "Adjective"],
    answer: 1,
    questionRef: "2023-paper1-q22b",
  },  {
    id: 71,
    q: "Select one option to show whether the underlined word is a <em class='bold'>verb</em>, a <em class='bold'>noun</em> or an <em class='bold'>adjective</em>.",
    q2: "We can <em class='underline'>magnetise</em> the nail",
    choices: ["Verb", "Noun", "Adjective"],
    answer: 0,
    questionRef: "2023-paper1-q22c",
  },  
  {
    id: 72,
    q: "Which sentence must end with a question mark?",
    choices: ["What happened that day might never be known", "What really happened that day", "Someone must know what really happened that day", "I'd like to know what happened that day"],
    answer: 1,
    questionRef: "paper1-2018-q2",
  },  {
    id: 73,
    q: "The prefix <em class='underline'>re-</em> can be added to the root word <em class='underline'>play</em> to make the word replay.", 
    q2: "Tick the meaning of the word replay.",
    choices: ["to play together", "to play later", "to play again", "to play badly"],
    answer: 2,
    questionRef: "paper1-2018-q3",
  },  
  {
    id: 74,
    q: "Is this sentence a <em class='bold'>question</em>, a <em class='bold'>statement</em> or a <em class='bold'>command</em>?",
    q2: "In autumn, many trees lose their leaves",
    choices: ["Question", "Statement", "Command"],
    answer: 1,
    questionRef: "paper1-2018-q4a",
  },
  {
    id: 75,
    q: "Is this sentence a <em class='bold'>question</em>, a <em class='bold'>statement</em> or a <em class='bold'>command</em>?",
    q2: "Look at the trees carefully",
    choices: ["Question", "Statement", "Command"],
    answer: 2,
    questionRef: "paper1-2018-q4b",
  },
  {
    id: 76,
    q: "Is this sentence a <em class='bold'>question</em>, a <em class='bold'>statement</em> or a <em class='bold'>command</em>?",
    q2: "Scientists are studying how trees can live for thousands of years",
    choices: ["Question", "Statement", "Command"],
    answer: 1,
    questionRef: "paper1-2018-q4c",
  },
  {
    id: 77,
    q: "Is this sentence a <em class='bold'>question</em>, a <em class='bold'>statement</em> or a <em class='bold'>command</em>?",
    q2: "How can you tell a tree’s age",
    choices: ["Question", "Statement", "Command"],
    answer: 0,
    questionRef: "paper1-2018-q4d",
  },  
  {
    id: 78,
    q: "Which word in the sentence below is an adverb?",
    q2: "The lively crowd cheered loudly when the rally car race began.",
    choices: ["lively", "loudly", "when", "rally"],
    answer: 1,
    questionRef: "paper1-2018-q6",
  },
  {
    id: 79,
    q: "Which sentence is grammatically correct?",
    choices: ["Tomorrow we went shopping at the sales.", "In three weeks' time, I will be on holiday.", "Next weekend, we had gone to the river to fish.", "Last summer, we swim at the beach and collect seashells."],
    answer: 1,
    questionRef: "paper1-2018-q8",
  },
  {
    id: 80,
    q: "Which verb is a <em class='bold'>synonym</em> of the verb <em class='underline'>produce</em>?",
    choices: ["make", "buy", "sell", "trade"],
    answer: 0,
    questionRef: "paper1-2018-q9",
  },
  {
    id: 81,
    q: "Which sentence is a command?",
    choices: ["You should bring a coat.", "You will need a coat in case it rains.", "I am going to bring a coat.", "Bring a coat in case it rains."],
    answer: 3,
    questionRef: "paper1-2018-q10",
  },
  {
    id: 82,
    q: "Which option completes the sentence in the <em class='bold'>past perfect</em>?", 
    q2: "Soon after a Frenchman __________ the first land speed record, it was broken.",
    choices: ["has set", "had set", "set", "was setting"],
    answer: 1,
    questionRef: "paper1-2018-q12",
  },
  {
    id: 83,
    q: "Which sentence is written in <em class='bold'>Standard English</em>?",
    choices: ["Two sports teams come to our school yesterday.", "My friend was tidying the classroom.", "Today the children done their school play.", "The teachers was going to send a letter next week."],
    answer: 1,
    questionRef: "paper1-2018-q13",
  },
  {
    id: 84,
    q: "Tick the sentence that uses a dash correctly.",
    choices: ["I find baking tricky - there are too many things to go wrong.", "I find baking tricky there are too many things - to go wrong.", "I find baking - tricky there are too many things to go wrong.", "I find baking tricky there are - too many things to go wrong."],
    answer: 0,
    questionRef: "paper1-2018-q14",
  },
  {
    id: 85,
    q: "What is the grammatical term for the underlined part of the sentence?", 
    q2: "<em class='underline'>Charlie spilt his juice</em>, but it didn't go on his shirt.",
    choices: ["an adverbial", "a main clause ", "a noun phrase", "a subordinate clause"],
    answer: 1,
    questionRef: "paper1-2018-q15",
  },
  {
    id: 86,
    q: "Which sentence must not end with an exclamation mark?",
    choices: ["What a hilarious film that was", "I loved the opening scene", "Was the ending funny", "I have never laughed so much"],
    answer: 2,
    questionRef: "paper1-2018-q16",
  },
  {
    id: 87,
    q: "Which sentence uses the underlined word as a noun?",
    choices: ["Dancers must be very <em class='underline'>fit</em> and athletic.", "Can I <em class='underline'>help</em> you with that jigsaw?", "We heard <em class='underline'>thunder</em>, but we did not see any lightning.", "The ocean is <em class='underline'>grey</em> and angry-looking today."],
    answer: 2,
    questionRef: "paper1-2018-q18",
  },
  {
    id: 88,
    q: "Which sentence is punctuated correctly?",
    choices: ["Lately, the days have been growing noticeably longer and, warmer.", "Lately the days, have been growing noticeably longer and warmer.", "Lately the days, have been growing noticeably longer, and warmer.", "Lately, the days have been growing noticeably longer and warmer."],
    answer: 3,
    questionRef: "paper1-2018-q19",
  },
  {
    id: 89,
    q: "Which word class is the underlined word in the sentence below?",
    q2: "My brother thinks that football is <em class='underline'>an</an> amazing game.",
    choices: ["adverb", "adjective", "determiner", "conjunction"],
    answer: 2,
    questionRef: "paper1-2018-q21",
  },
  {
    id: 90,
    q: "Which sentence is the most formal?",
    choices: ["Watching too much television should be avoided.", "You shouldn't watch too much TV.", "Watching lots of TV isn't a good idea.", "You really should try not to watch loads of telly."],
    answer: 0,
    questionRef: "paper1-2018-q25",
  },
  {
    id: 91,
    q: "Select the most <em class='bold'>formal</em> option to complete the sentence.",
    q2: "We would like to invite you to a __________",
    choices: ["catch-up", "celebration", "get-together"],
    answer: 1,
    questionRef: "paper1-2018-q29a",
  },
  {
    id: 92,
    q: "Select the most <em class='bold'>formal</em> option to complete the sentence.",
    q2: "You are invited to a celebration to mark this ________ occasion",
    choices: ["fab", "really cool", "momentous"],
    answer: 2,
    questionRef: "paper1-2018-q29b",
  },
  {
    id: 93,
    q: "Select the most <em class='bold'>formal</em> option to complete the sentence.",
    q2: "The party will ___________ at 5pm.",
    choices: ["start up", "commence", "kick off"],
    answer: 1,
    questionRef: "paper1-2018-q29c",
  },
  {
    id: 94,
    q: "Is the underlined noun is <em class='bold'>singular</em> or <em class='bold'>plural</em>",
    q2: "The <em class='underline'>customers'</em> hunger was satisfied by the pizza.",
    choices: ["singular", "plural"],
    answer: 1,
    questionRef: "paper1-2018-q30a",
  },
  {
    id: 95,
    q: "Is the underlined noun is <em class='bold'>singular</em> or <em class='bold'>plural</em>",
    q2: "The <em class='underline'>princess's</em> slippers were made  of glass.",
    choices: ["singular", "plural"],
    answer: 0,
    questionRef: "paper1-2018-q30a",
  },
  {
    id: 96,
    q: "Is the underlined noun is <em class='bold'>singular</em> or <em class='bold'>plural</em>",
    q2: "Those are the <em class='underline'>boys'</em> books.",
    choices: ["singular", "plural"],
    answer: 1,
    questionRef: "paper1-2018-q30a",
  },
  {
    id: 97,
    q: "Which sentence is the most formal?",
    choices: ["She suggested that her mother be present.", "She really hopes to be ready on time.", "Don't forget to lock the door!", "If Johnny's late, we'll start without him."],
    answer: 0,
    questionRef: "paper1-2018-q32",
  },
  {
    id: 98,
    q: "Is this sentence written in the <em class = 'bold'>active</em> or the <em class = 'bold'>passive</em>.",
    q2: "The lost dog was found by the children.",
    choices: ["Active", "passive"],
    answer: 1,
    questionRef: "paper1-2018-q40a",
  },
  {
    id: 99,
    q: "Is this sentence written in the <em class = 'bold'>active</em> or the <em class = 'bold'>passive</em>.",
    q2: "Everyone heard the thunder.",
    choices: ["Active", "passive"],
    answer: 0,
    questionRef: "paper1-2018-q40b",
  },
  {
    id: 100,
    q: "Is this sentence written in the <em class = 'bold'>active</em> or the <em class = 'bold'>passive</em>.",
    q2: "Nicole was riding her bike.",
    choices: ["Active", "passive"],
    answer: 0,
    questionRef: "paper1-2018-q40c",
  },
  {
    id: 101,
    q: "Tick the sentence that must end with a <em class='bold'>question mark</em>.",
    choices: ["Why he went there was a mystery", "What he thinks about the problem is anyone's guess", "When are your cousins expected to arrive", "How they would get to the match was unclear"],
    answer: 2,
    questionRef: "paper1-2017-q1",
  },
  {
    id: 102,
    q: "Which sentence uses <em class='bold'>capital letters</em> correctly?",
    choices: ["We went to manchester for Kajal and Jamal's party.", "we went to Manchester for Kajal and Jamal's party.", "We went to Manchester for Kajal and Jamal's party.", "We went to Manchester for Kajal and Jamal's Party."],
    answer: 2,
    questionRef: "paper1-2017-q3",
  },
  {
    id: 103,
    q: "The <em class='bold'>prefix</em> <em class='underline'>mis-</em> can be added to the word <em class='underline'>read</em> to make the word <em class='underline'>misread</em>.", 
    q2: "What does the word <em class='bold'>misread</em> mean?",
    choices: ["to read quickly", "to read incorrectly", "to read again", "to read before"],
    answer: 1,
    questionRef: "paper1-2017-q4",
  },
  {
    id: 104,
    q: "Which <em class='bold'>verb form</em> completes the sentence?",
    q2: "After Disha _______________ her medal, she gave a television interview.",
    choices: ["is collecting", "had collected", "has collected", "was collecting"],
    answer: 1,
    questionRef: "paper1-2017-q5",
  },
  {
    id: 105,  
    q: "Select the correct <em class='bold'>verb form</em> to complete the sentences below.",
    q2: "The last place I saw Jack and Gwen ____ in the playground.",
    choices: ["was", "were"],
    answer: 0,
    questionRef: "paper1-2017-q6a",
  },
  {
    id: 106,
    q: "Select the correct <em class='bold'>verb form</em> to complete the sentences below.",
    q2: "At the museum, there ____ many interesting exhibits.",
    choices: ["was", "were"],
    answer: 1,
    questionRef: "paper1-2017-q6b",
  },
  {
    id: 107,
    q: "Select the correct <em class='bold'>verb form</em> to complete the sentences below.",
    q2: "The bikes ____ lined up for the start of the race. ",
    choices: ["was", "were"],
    answer: 1,
    questionRef: "paper1-2017-q6c",
  },
  {
    id: 108,
    q: "Tick the option that correctly completes the sentence below.",
    q2: "________________________   an official Olympic sport at the Winter Olympics in Japan.",
    choices: ["In 1998 snowboarding became,", "In 1998 snowboarding, became", "In, 1998 snowboarding became", "In 1998, snowboarding became"],
    answer: 3,
    questionRef: "paper1-2017-q7",
  },
  {
    id: 109,
    q: "Which sentence is punctuated correctly?",
    choices: [
    "Joe went upstairs, turned on his computer took out his homework and started.", 
    "Joe went upstairs turned on his computer, took out his homework, and started.", 
    "Joe went, upstairs turned on his computer, took out his homework, and started.", 
    "Joe went upstairs, turned on his computer, took out his homework and started."],
    answer: 3,
    questionRef: "paper1-2017-q8",
  },
  {
    id: 110,
    q: "What is the word class of the underlined word in the sentence below?", 
    q2: "The alarm rang and Jamal immediately jumped out of bed.",
    choices: ["conjunction", "adverb", "verb", "determiner"],
    answer: 1,
    questionRef: "paper1-2017-q9",
  },
  {
    id: 111,
    q: "What is the <em class='bold'>word class</em> of the underlined words in the  sentence below?",
    q2: "<em class='underline'>The</em> girl brought a sandwich and <em class='underline'>an</em> apple to eat for lunch.",
    choices: ["adjectives", "adverbs", "determiners", "nouns"],
    answer: 2,
    questionRef: "paper1-2017-q11",
  },
  {
    id: 112,
    q: "Which sentence is punctuated correctly?",
    choices: [
      "The man grabbed his coat &#8211; it looked cold and windy outside.", 
      "The man grabbed his coat it looked cold &#8211; and windy outside.", 
      "The man grabbed his coat it looked cold and windy &#8211; outside.", 
      "The man grabbed his coat it looked &#8211; cold and windy outside."],
    answer: 0,
    questionRef: "paper1-2017-q12",
  },
  {
    id: 113,
    q: "Which sentence uses the word <em class='underline'>round</em> as an <em class='bold'>adjective</em>?",
    choices: ["The dog ran <em class='underline'>round</em> in circles.", 
    "There was a <em class='underline'>round</em> of applause.", 
    "The castle had a <em class='underline'>round</em> tower.", 
    "The team has already made the final <em class='underline'>round</em>."],
    answer: 2,
    questionRef: "paper1-2017-q13",
  },
  {
    id: 114,
    q: "Which sentence is punctuated correctly?",
    choices: ["The town is ten miles (16 kilometres) away.", 
    "The town is ten miles (16 kilometres away.)", 
    "The town is ten miles (16) kilometres away.", 
    "The town is ten miles (16 kilometres away)."],
    answer: 0,
    questionRef: "paper1-2017-q14",
  },
  {
    id: 115,
    q: "Which sentence uses <em class='bold'>capital letters</em> correctly?",
    choices: ["We are going to see a Play by Shakespeare.", 
    "There is a new Doctor at the local Hospital.", 
    "There is a Class Visit to the museum next week.", 
    "He is trying to swim the English Channel."],
    answer: 3,
    questionRef: "paper1-2017-q15",
  },
  {
    id: 116,
    q: "Which sentence is an <em class='bold'>exclamation</em>?",
    choices: ["What time did the sun set last night", 
    "She said the sunset was particularly beautiful", 
    "What a spectacular sunset that is", 
    "The sunsets are lovely at this time of year"],
    answer: 2,
    questionRef: "paper1-2017-q17",
  },
  {
    id: 117,
    q: "Which sentence uses the word <em class='underline'>book</em> as a <em class='bold'>verb</em>?",
    choices: ["We decided to <em class='underline'>book</em> tickets for the football match.", 
    "Arin wrote a <em class='underline'>book</em> review for the school magazine.", 
    "The scientist's ideas are explained in his latest <em class='underline'>book</em>.", 
    "<em class='underline'>Book</em> club meets every Wednesday in the library."],
    answer: 0,
    questionRef: "paper1-2017-q18",
  },
  {
    id: 118,
    q: "Which sentence is punctuated correctly?",
    choices: ["Abdul called out, “will you come and help me?”", 
    "Abdul called out “Will you come and help me”", 
    "Abdul called out, “Will you come and help me”?", 
    "Abdul called out, “Will you come and help me?”"],
    answer: 3,
    questionRef: "paper1-2017-q21",
  },
  {
    id: 119,
    q: "Which sentence is the most <em class='bold'>formal</em>?",
    choices: ["Your presence is requested at the wedding of our daughter.", 
    "You would like to come to our daughter's wedding, wouldn't you?", 
    "We'd love you to join us for our daughter's wedding.", 
    "Our daughter's getting married - please come!"],
    answer: 0,
    questionRef: "paper1-2017-q22",
  },
  {
    id: 120,
    q: "Which underlined group of words is a <em class='bold'>subordinate clause</em>?",
    choices: ["If you want to, <em class='underline'>you can walk with us</em>.", 
    "<em class='underline'>This is the best fishing spot</em> we have found.", 
    "We change places <em class='underline'>when the bell rings</em>.", 
    "<em class='underline'>We planted the parsley</em> next to the mint."],
    answer: 2,
    questionRef: "paper1-2017-q23",
  },
  {
    id: 121,
    q: "Is the apostrophe in the sentence below used for a <em class='bold'>contracted form</em> or <em class='bold'>possession</em>?",
    q2: "Where is Karen's pen?",
    choices: ["Contracted form", "Possession"],
    answer: 1,
    questionRef: "paper1-2017-q25a",
  },
  {
    id: 122,
    q: "Is the apostrophe in the sentence below used for a <em class='bold'>contracted form</em> or <em class='bold'>possession</em>?",
    q2: "Joshua's hungry",
    choices: ["Contracted form", "Possession"],
    answer: 0,
    questionRef: "paper1-2017-q25b",
  },
  {
    id: 123,
    q: "Is the apostrophe in the sentence below used for a <em class='bold'>contracted form</em> or <em class='bold'>possession</em>?",
    q2: "Please get the dog's dinner",
    choices: ["Contracted form", "Possession"],
    answer: 1,
    questionRef: "paper1-2017-q25c",
  },
  {
    id: 124,
    q: "Is the apostrophe in the sentence below used for a <em class='bold'>contracted form</em> or <em class='bold'>possession</em>?",
    q2: "The cat's outside",
    choices: ["Contracted form", "Possession"],
    answer: 0,
    questionRef: "paper1-2017-q25d",
  },
  {
    id: 125,
    q: "Which sentence contains a <em class='bold'>relative clause</em>?",
    choices: ["The boy who I met at the park is in my class.", 
    "The team is going to play a match tomorrow.", 
    "Sue said that she wanted to learn to play the drums.", 
    "Whenever they have time, they like to go cycling."],
    answer: 0,
    questionRef: "paper1-2017-q26",
  },
  {
    id: 126,
    q: "Which sentence is a <em class='bold'>statement</em>?",
    choices: ["You can copy the pattern from a book", 
    "Be careful when you use the glue", 
    "Do you use glitter to decorate the edges", 
    "Do not touch the paint until it is dry"],
    answer: 0,
    questionRef: "paper1-2017-q27",
  },
  {
    id: 127,
    q: "What is the <em class='bold'>subject</em> of the sentence below?",
    q2: "On Tuesday, Mary plans to meet Aidan in Liverpool.",
    choices: ["Tuesday", "Mary", "Aidan", "Liverpool"],
    answer: 1,
    questionRef: "paper1-2017-q35",
  },
  {
    id: 129,
    q: "Which punctuation mark should be used in the place indicated by the arrow?",
    q2: "Josh was excellent at languages <sub>&uarr;</sub> he spoke French and Spanish.",
    choices: ["comma", "hyphen", "full stop", "semi-colon"],
    answer: 3,
    questionRef: "paper1-2016-q43",
  },
 {
    id: 130,
    q: "Tick the option that must end with a <em class ='bold'>question mark</em>.",
    choices: ["What we ate for dinner was very unusual", "Can you guess what we ate for dinner", "Ask me what we ate for dinner", "I will tell you what we ate for dinner"],
    answer: 1,
    questionRef: "paper1-2016-q5",
  },
   {
    id: 131,
    q: "Which sentence uses the <em class ='bold'>colon</em> correctly?",
    choices: ["I bought several beach toys a bucket: a spade a ball and a kite.", "I bought several beach toys a: bucket, a spade, a ball and a kite.", 
    "I bought several beach toys: a bucket, a spade, a ball and a kite.", "I bought several: beach toys, a bucket, a spade, a ball and a kite."],
    answer: 2,
    questionRef: "paper1-2016-q6",
  },
   {
    id: 132,
    q: "Is the sentence below in the <em class ='bold'>present progressive</em> or the <em class ='bold'>past progressive</em>.",
    q2: "Joey was playing football in the park after school.", 
    choices: ["Present progressive", "Past progressive"],
    answer: 1,
    questionRef: "paper1-2016-q10a",
  },
   {
    id: 133,
    q: "Is the sentence below in the <em class ='bold'>present progressive</em> or the <em class ='bold'>past progressive</em>.",
    q2: "Joey's football skills are improving all the time.", 
    choices: ["Present progressive", "Past progressive"],
    answer: 0,
    questionRef: "paper1-2016-q10b",
  },
   {
    id: 134,
    q: "Is the sentence below in the <em class ='bold'>present progressive</em> or the <em class ='bold'>past progressive</em>.",
    q2: "Joey is hoping to be a professional footballer.", 
    choices: ["Present progressive", "Past progressive"],
    answer: 0,
    questionRef: "paper1-2016-q10c",
  },
   {
    id: 135,
    q: "Which sentence uses the <em class='bold'>hyphen</em> correctly?",
    choices: ["The sugar-free lollies are available in three flavours.", 
    "The sugar-free-lollies are available in three flavours.", 
    "The sugar-free lollies are available in three-flavours.", 
  "The sugar free-lollies are available in three flavours."],
    answer: 0,
    questionRef: "paper1-2016-q12",
  },
   {
    id: 136,
    q: "Which sentence shows that you are <em class='bold'>most likely</em> to be away next week?",
    choices: [
    "I could be away next week.", 
    "I might be away next week.", 
    "I shall be away next week.", 
  "I may be away next week."],
    answer: 2,
    questionRef: "paper1-2016-q13",
  },
   {
    id: 137,
    q: "Which sentence is written in Standard English?",
    choices: ["I went to the library and done my homework.", 
    "They seen their friends at the cinema.", 
    "I been to the circus with my aunt and uncle.", 
  "I sang with the school choir in the concert."],
    answer: 3,
    questionRef: "paper1-2016-q15",
  },
   {
    id: 138,
    q: "Which sentence uses capital letters correctly?",
    choices: [
    "The athlete won four gold medals at the olympic games in London.", 
    "The athlete won four Gold Medals at the Olympic Games in London.", 
    "The athlete won four Gold medals at the Olympic games in London.", 
    "The athlete won four gold medals at the Olympic Games in London."],
    answer: 3,
    questionRef: "paper1-2016-q19",
  },
   {
    id: 139,
    q: "What does the root <em class='underline'>graph</em> mean in the word family below?",
    q2: "<pre>graphics    autograph    photography    paragraph</pre>",
    choices: ["moving pictures", "drawing or writing", "colourful or bright", "in a group"],
    answer: 1,
    questionRef: "paper1-2016-q",
  },
  //  {
  //   id: 140,
  //   q: "Tick one box in each row to show whether the commas are used correctly in the sentence.",
  // q2: "",
  //   choices: ["Commas used correctly", "Commas not used correctly"],
  //   answer: [],
  //   questionRef: "paper1-2016-q23a",
  // },

  //  {
  //   id: 141,
  //   q: "Tick one box in each row to show whether the commas are used correctly in the sentence.",
  // q2: "",
  //   choices: ["Commas used correctly", "Commas not used correctly"],
  //   answer: [],
  //   questionRef: "paper1-2016-q23b",
  // },

  //  {
  //   id: 142,
  //   q: "Tick one box in each row to show whether the commas are used correctly in the sentence.",
  // q2: "",
  //   choices: ["Commas used correctly", "Commas not used correctly"],
  //   answer: [],
  //   questionRef: "paper1-2016-q23c",
  // },

  //  {
  //   id: 143,
  //   q: "Tick one box in each row to show whether the commas are used correctly in the sentence.",
  // q2: "",
  //   choices: ["Commas used correctly", "Commas not used correctly"],
  //   answer: [],
  //   questionRef: "paper1-2016-q23d",
  // },

  // {
  //   id: 144,
  //   q: "exampleToCopy",
  //   choices: ["", "", ""],
  //   answer: 0,
  //   questionRef: "paper1-2016-q",
  // },
  // {
  //   id: 145,
  //   q: "exampleToCopy",
  //   choices: ["", "", ""],
  //   answer: 0,
  //   questionRef: "paper1-2016-q",
  // },
  // {
  //   id: 146,
  //   q: "exampleToCopy",
  //   choices: ["", "", ""],
  //   answer: 0,
  //   questionRef: "paper1-2016-q",
  // },
  // {
  //   id: 147,
  //   q: "exampleToCopy",
  //   choices: ["", "", ""],
  //   answer: 0,
  //   questionRef: "paper1-2016-q",
  // },
  // {
  //   id: 148,
  //   q: "exampleToCopy",
  //   choices: ["", "", ""],
  //   answer: 0,
  //   questionRef: "paper1-2016-q",
  // },
  // {
  //   id: 149,
  //   q: "exampleToCopy",
  //   choices: ["", "", ""],
  //   answer: 0,
  //   questionRef: "paper1-2016-q",
  // },
  // {
  //   id: 140,
  //   q: "exampleToCopy",
  //   choices: ["", "", ""],
  //   answer: 0,
  //   questionRef: "paper1-2016-q",
  // },
  // {
  //   id: 140,
  //   q: "exampleToCopy",
  //   choices: ["", "", ""],
  //   answer: 0,
  //   questionRef: "paper1-2016-q",
  // },
  // {
  //   id: 140,
  //   q: "exampleToCopy",
  //   choices: ["", "", ""],
  //   answer: 0,
  //   questionRef: "paper1-2016-q",
  // },


  // {
  //   id: 50,
  //   q: "exampleToCopy",
  //   choices: ["", "", ""],
  //   answer: 0,
  //   questionRef: "2019-paper1-q",
  // },
  // example of an image-based question
  // {
  //   id: 11,
  //   q: "How many squares are showing in this pic?",
  //   choices: ["3", "2", "1"],
  //   answer: 2,
  //   img: "img/square.jpg"
  // questionRef:
  //   }
];

// Commented out on 3/1/2024 as this question has been answered correctly several times in a row.
  // {
  //   id: 10,
  //   q: "Select the sentence that shows Lara is <em class='bold'>most likely</em> to go swimming on Saturday.",
  //   choices: [
  //     "Lara will go swimming on Saturday.",
  //     "Lara should go swimming on Saturday.",
  //     "Lara might go swimming on Saturday.",
  //     "Lara could go swimming on Saturday.",
  //   ],
  //   answer: 0,
  //   questionRef: "2023-paper1-q9",
  // },
